services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./backend/upload/images:/app/upload/images

  frontend:
    build:
      context: ./frontend/simple-news
      dockerfile: Dockerfile
    env_file:
      - ./frontend/simple-news/.env.docker
    container_name: frontend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
        restart: true

networks:
  app-network:
    driver: bridge

volumes:
  app-db-data: